// <auto-generated />
using System;
using Clinic.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clinic.Services.Migrations
{
    [DbContext(typeof(ClinicDbContext))]
    [Migration("20260310124026_SeedSampleData1")]
    partial class SeedSampleData1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivityType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("Activities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActivityType = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đăng ký bệnh nhân mới: Hoàng Minh Anh",
                            EntityId = 1,
                            EntityType = "Patient",
                            PatientId = 1
                        },
                        new
                        {
                            Id = 2,
                            ActivityType = 0,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Tạo lịch hẹn tái khám",
                            EntityId = 1,
                            EntityType = "Appointment",
                            PatientId = 1,
                            StaffId = 1
                        },
                        new
                        {
                            Id = 3,
                            ActivityType = 3,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Lên lịch phẫu thuật ruột thừa",
                            EntityId = 1,
                            EntityType = "SurgerySchedule",
                            PatientId = 3,
                            StaffId = 3
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduledAt");

                    b.HasIndex("StaffId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PatientId = 1,
                            Reason = "Tái khám",
                            ScheduledAt = new DateTime(2024, 3, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = 1,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DurationMinutes = 30,
                            PatientId = 2,
                            Reason = "Khám tổng quát",
                            ScheduledAt = new DateTime(2024, 3, 21, 9, 0, 0, 0, DateTimeKind.Utc),
                            StaffId = 1,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.HealthRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Diagnosis")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("VisitDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("StaffId");

                    b.ToTable("HistoryRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Cảm cúm nhẹ",
                            Notes = "Nghỉ ngơi, uống nhiều nước",
                            PatientId = 1,
                            StaffId = 1,
                            Symptoms = "Sốt, đau họng",
                            VisitDate = new DateTime(2024, 2, 10, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Diagnosis = "Khám sức khỏe định kỳ",
                            Notes = "Kết quả tốt",
                            PatientId = 2,
                            StaffId = 1,
                            Symptoms = "Không",
                            VisitDate = new DateTime(2024, 2, 15, 9, 30, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("InsuranceNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Phone");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường ABC, Quận 1, TP.HCM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1985, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoangminh@email.com",
                            FullName = "Hoàng Minh Anh",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "0912345678"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường XYZ, Quận 3, TP.HCM",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Nguyễn Thị Bình",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "0912345679"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1978, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Trần Văn Cường",
                            Gender = "Nam",
                            IdentityNumber = "012345678901",
                            IsActive = true,
                            Phone = "0912345680"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Địa chỉ demo 4",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 4",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Địa chỉ demo 5",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 5",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000005"
                        },
                        new
                        {
                            Id = 6,
                            Address = "Địa chỉ demo 6",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 6",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000006"
                        },
                        new
                        {
                            Id = 7,
                            Address = "Địa chỉ demo 7",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 7",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000007"
                        },
                        new
                        {
                            Id = 8,
                            Address = "Địa chỉ demo 8",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 8",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000008"
                        },
                        new
                        {
                            Id = 9,
                            Address = "Địa chỉ demo 9",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 9",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000009"
                        },
                        new
                        {
                            Id = 10,
                            Address = "Địa chỉ demo 10",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 10",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000010"
                        },
                        new
                        {
                            Id = 11,
                            Address = "Địa chỉ demo 11",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 11",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000011"
                        },
                        new
                        {
                            Id = 12,
                            Address = "Địa chỉ demo 12",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 12",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000012"
                        },
                        new
                        {
                            Id = 13,
                            Address = "Địa chỉ demo 13",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 13",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000013"
                        },
                        new
                        {
                            Id = 14,
                            Address = "Địa chỉ demo 14",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 14",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000014"
                        },
                        new
                        {
                            Id = 15,
                            Address = "Địa chỉ demo 15",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 15",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000015"
                        },
                        new
                        {
                            Id = 16,
                            Address = "Địa chỉ demo 16",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 16",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000016"
                        },
                        new
                        {
                            Id = 17,
                            Address = "Địa chỉ demo 17",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 17",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000017"
                        },
                        new
                        {
                            Id = 18,
                            Address = "Địa chỉ demo 18",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 18",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000018"
                        },
                        new
                        {
                            Id = 19,
                            Address = "Địa chỉ demo 19",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 19",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000019"
                        },
                        new
                        {
                            Id = 20,
                            Address = "Địa chỉ demo 20",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 20",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000020"
                        },
                        new
                        {
                            Id = 21,
                            Address = "Địa chỉ demo 21",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 21",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000021"
                        },
                        new
                        {
                            Id = 22,
                            Address = "Địa chỉ demo 22",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 22",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000022"
                        },
                        new
                        {
                            Id = 23,
                            Address = "Địa chỉ demo 23",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 23",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000023"
                        },
                        new
                        {
                            Id = 24,
                            Address = "Địa chỉ demo 24",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 24",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000024"
                        },
                        new
                        {
                            Id = 25,
                            Address = "Địa chỉ demo 25",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 25",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000025"
                        },
                        new
                        {
                            Id = 26,
                            Address = "Địa chỉ demo 26",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 26",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000026"
                        },
                        new
                        {
                            Id = 27,
                            Address = "Địa chỉ demo 27",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 27",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000027"
                        },
                        new
                        {
                            Id = 28,
                            Address = "Địa chỉ demo 28",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 28",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000028"
                        },
                        new
                        {
                            Id = 29,
                            Address = "Địa chỉ demo 29",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 29",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000029"
                        },
                        new
                        {
                            Id = 30,
                            Address = "Địa chỉ demo 30",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 30",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000030"
                        },
                        new
                        {
                            Id = 31,
                            Address = "Địa chỉ demo 31",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 31",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000031"
                        },
                        new
                        {
                            Id = 32,
                            Address = "Địa chỉ demo 32",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 32",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000032"
                        },
                        new
                        {
                            Id = 33,
                            Address = "Địa chỉ demo 33",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 33",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000033"
                        },
                        new
                        {
                            Id = 34,
                            Address = "Địa chỉ demo 34",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 34",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000034"
                        },
                        new
                        {
                            Id = 35,
                            Address = "Địa chỉ demo 35",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 35",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000035"
                        },
                        new
                        {
                            Id = 36,
                            Address = "Địa chỉ demo 36",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 36",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000036"
                        },
                        new
                        {
                            Id = 37,
                            Address = "Địa chỉ demo 37",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 37",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000037"
                        },
                        new
                        {
                            Id = 38,
                            Address = "Địa chỉ demo 38",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 38",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000038"
                        },
                        new
                        {
                            Id = 39,
                            Address = "Địa chỉ demo 39",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 39",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000039"
                        },
                        new
                        {
                            Id = 40,
                            Address = "Địa chỉ demo 40",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 40",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000040"
                        },
                        new
                        {
                            Id = 41,
                            Address = "Địa chỉ demo 41",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 41",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000041"
                        },
                        new
                        {
                            Id = 42,
                            Address = "Địa chỉ demo 42",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 42",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000042"
                        },
                        new
                        {
                            Id = 43,
                            Address = "Địa chỉ demo 43",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 43",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000043"
                        },
                        new
                        {
                            Id = 44,
                            Address = "Địa chỉ demo 44",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 44",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000044"
                        },
                        new
                        {
                            Id = 45,
                            Address = "Địa chỉ demo 45",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 45",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000045"
                        },
                        new
                        {
                            Id = 46,
                            Address = "Địa chỉ demo 46",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 46",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000046"
                        },
                        new
                        {
                            Id = 47,
                            Address = "Địa chỉ demo 47",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 47",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000047"
                        },
                        new
                        {
                            Id = 48,
                            Address = "Địa chỉ demo 48",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 48",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000048"
                        },
                        new
                        {
                            Id = 49,
                            Address = "Địa chỉ demo 49",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 49",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000049"
                        },
                        new
                        {
                            Id = 50,
                            Address = "Địa chỉ demo 50",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 50",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000050"
                        },
                        new
                        {
                            Id = 51,
                            Address = "Địa chỉ demo 51",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 51",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000051"
                        },
                        new
                        {
                            Id = 52,
                            Address = "Địa chỉ demo 52",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 52",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000052"
                        },
                        new
                        {
                            Id = 53,
                            Address = "Địa chỉ demo 53",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 53",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000053"
                        },
                        new
                        {
                            Id = 54,
                            Address = "Địa chỉ demo 54",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 54",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000054"
                        },
                        new
                        {
                            Id = 55,
                            Address = "Địa chỉ demo 55",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 55",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000055"
                        },
                        new
                        {
                            Id = 56,
                            Address = "Địa chỉ demo 56",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 56",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000056"
                        },
                        new
                        {
                            Id = 57,
                            Address = "Địa chỉ demo 57",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 57",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000057"
                        },
                        new
                        {
                            Id = 58,
                            Address = "Địa chỉ demo 58",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 58",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000058"
                        },
                        new
                        {
                            Id = 59,
                            Address = "Địa chỉ demo 59",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 59",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000059"
                        },
                        new
                        {
                            Id = 60,
                            Address = "Địa chỉ demo 60",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 60",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000060"
                        },
                        new
                        {
                            Id = 61,
                            Address = "Địa chỉ demo 61",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 61",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000061"
                        },
                        new
                        {
                            Id = 62,
                            Address = "Địa chỉ demo 62",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 62",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000062"
                        },
                        new
                        {
                            Id = 63,
                            Address = "Địa chỉ demo 63",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 63",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000063"
                        },
                        new
                        {
                            Id = 64,
                            Address = "Địa chỉ demo 64",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 64",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000064"
                        },
                        new
                        {
                            Id = 65,
                            Address = "Địa chỉ demo 65",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 65",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000065"
                        },
                        new
                        {
                            Id = 66,
                            Address = "Địa chỉ demo 66",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 66",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000066"
                        },
                        new
                        {
                            Id = 67,
                            Address = "Địa chỉ demo 67",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 67",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000067"
                        },
                        new
                        {
                            Id = 68,
                            Address = "Địa chỉ demo 68",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 68",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000068"
                        },
                        new
                        {
                            Id = 69,
                            Address = "Địa chỉ demo 69",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 69",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000069"
                        },
                        new
                        {
                            Id = 70,
                            Address = "Địa chỉ demo 70",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 70",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000070"
                        },
                        new
                        {
                            Id = 71,
                            Address = "Địa chỉ demo 71",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 71",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000071"
                        },
                        new
                        {
                            Id = 72,
                            Address = "Địa chỉ demo 72",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 72",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000072"
                        },
                        new
                        {
                            Id = 73,
                            Address = "Địa chỉ demo 73",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 73",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000073"
                        },
                        new
                        {
                            Id = 74,
                            Address = "Địa chỉ demo 74",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 74",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000074"
                        },
                        new
                        {
                            Id = 75,
                            Address = "Địa chỉ demo 75",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 75",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000075"
                        },
                        new
                        {
                            Id = 76,
                            Address = "Địa chỉ demo 76",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 76",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000076"
                        },
                        new
                        {
                            Id = 77,
                            Address = "Địa chỉ demo 77",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 77",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000077"
                        },
                        new
                        {
                            Id = 78,
                            Address = "Địa chỉ demo 78",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 78",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000078"
                        },
                        new
                        {
                            Id = 79,
                            Address = "Địa chỉ demo 79",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 79",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000079"
                        },
                        new
                        {
                            Id = 80,
                            Address = "Địa chỉ demo 80",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 80",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000080"
                        },
                        new
                        {
                            Id = 81,
                            Address = "Địa chỉ demo 81",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 81",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000081"
                        },
                        new
                        {
                            Id = 82,
                            Address = "Địa chỉ demo 82",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 82",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000082"
                        },
                        new
                        {
                            Id = 83,
                            Address = "Địa chỉ demo 83",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 83",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000083"
                        },
                        new
                        {
                            Id = 84,
                            Address = "Địa chỉ demo 84",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 84",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000084"
                        },
                        new
                        {
                            Id = 85,
                            Address = "Địa chỉ demo 85",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 85",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000085"
                        },
                        new
                        {
                            Id = 86,
                            Address = "Địa chỉ demo 86",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 86",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000086"
                        },
                        new
                        {
                            Id = 87,
                            Address = "Địa chỉ demo 87",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 87",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000087"
                        },
                        new
                        {
                            Id = 88,
                            Address = "Địa chỉ demo 88",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 88",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000088"
                        },
                        new
                        {
                            Id = 89,
                            Address = "Địa chỉ demo 89",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 89",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000089"
                        },
                        new
                        {
                            Id = 90,
                            Address = "Địa chỉ demo 90",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 90",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000090"
                        },
                        new
                        {
                            Id = 91,
                            Address = "Địa chỉ demo 91",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 91",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000091"
                        },
                        new
                        {
                            Id = 92,
                            Address = "Địa chỉ demo 92",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 92",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000092"
                        },
                        new
                        {
                            Id = 93,
                            Address = "Địa chỉ demo 93",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 93",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000093"
                        },
                        new
                        {
                            Id = 94,
                            Address = "Địa chỉ demo 94",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 94",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000094"
                        },
                        new
                        {
                            Id = 95,
                            Address = "Địa chỉ demo 95",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 95",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000095"
                        },
                        new
                        {
                            Id = 96,
                            Address = "Địa chỉ demo 96",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 96",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000096"
                        },
                        new
                        {
                            Id = 97,
                            Address = "Địa chỉ demo 97",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 97",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000097"
                        },
                        new
                        {
                            Id = 98,
                            Address = "Địa chỉ demo 98",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 98",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000098"
                        },
                        new
                        {
                            Id = 99,
                            Address = "Địa chỉ demo 99",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 99",
                            Gender = "Nữ",
                            IsActive = true,
                            Phone = "090000099"
                        },
                        new
                        {
                            Id = 100,
                            Address = "Địa chỉ demo 100",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DateOfBirth = new DateTime(1990, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Bệnh nhân demo 100",
                            Gender = "Nam",
                            IsActive = true,
                            Phone = "090000100"
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Dosage")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Frequency")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("HealthRecordId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("HealthRecordId");

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Dosage = "1 viên",
                            Duration = "5 ngày",
                            Frequency = "3 lần/ngày",
                            HealthRecordId = 1,
                            Instructions = "Uống sau ăn",
                            IsActive = true,
                            MedicineName = "Paracetamol 500mg"
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Staff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Specialization")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StaffType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.ToTable("Staff");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor1@clinic.com",
                            FullName = "Nguyễn Văn Bác sĩ",
                            IsActive = true,
                            Phone = "0901234567",
                            Specialization = "Nội tổng quát",
                            StaffType = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nurse1@clinic.com",
                            FullName = "Trần Thị Y tá",
                            IsActive = true,
                            Phone = "0901234568",
                            StaffType = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "doctor2@clinic.com",
                            FullName = "Lê Văn Phẫu thuật",
                            IsActive = true,
                            Phone = "0901234569",
                            Specialization = "Ngoại khoa",
                            StaffType = 0
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "nurse2@clinic.com",
                            FullName = "Phạm Thị Điều dưỡng",
                            IsActive = true,
                            Phone = "0901234570",
                            StaffType = 1
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.SurgerySchedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Room")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SurgeryType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduledAt");

                    b.ToTable("SurgerySchedules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Nội soi cắt ruột thừa",
                            DurationMinutes = 120,
                            PatientId = 3,
                            Room = "Phòng 101",
                            ScheduledAt = new DateTime(2024, 3, 25, 7, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            SurgeryType = "Phẫu thuật ruột thừa"
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.SurgeryScheduleStaff", b =>
                {
                    b.Property<int>("SurgeryScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("TeamRole")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("SurgeryScheduleId", "StaffId");

                    b.HasIndex("StaffId");

                    b.ToTable("SurgeryScheduleStaff");

                    b.HasData(
                        new
                        {
                            SurgeryScheduleId = 1,
                            StaffId = 3,
                            TeamRole = "Surgeon"
                        });
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("StaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("StaffId")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Activity", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.Patient", "Patient")
                        .WithMany("Activities")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Clinic.Services.Domain.Entities.Staff", "Staff")
                        .WithMany("Activities")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Services.Domain.Entities.Staff", "Staff")
                        .WithMany("Appointments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.HealthRecord", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.Patient", "Patient")
                        .WithMany("HistoryRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Services.Domain.Entities.Staff", "Staff")
                        .WithMany("HistoryRecords")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Prescription", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.HealthRecord", "HealthRecord")
                        .WithMany("Prescriptions")
                        .HasForeignKey("HealthRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HealthRecord");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.SurgerySchedule", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.Patient", "Patient")
                        .WithMany("SurgerySchedules")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.SurgeryScheduleStaff", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.Staff", "Staff")
                        .WithMany("SurgeryAssignments")
                        .HasForeignKey("StaffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Clinic.Services.Domain.Entities.SurgerySchedule", "SurgerySchedule")
                        .WithMany("TeamMembers")
                        .HasForeignKey("SurgeryScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");

                    b.Navigation("SurgerySchedule");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.UserAccount", b =>
                {
                    b.HasOne("Clinic.Services.Domain.Entities.Staff", "Staff")
                        .WithOne("UserAccount")
                        .HasForeignKey("Clinic.Services.Domain.Entities.UserAccount", "StaffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.HealthRecord", b =>
                {
                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Appointments");

                    b.Navigation("HistoryRecords");

                    b.Navigation("SurgerySchedules");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.Staff", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Appointments");

                    b.Navigation("HistoryRecords");

                    b.Navigation("SurgeryAssignments");

                    b.Navigation("UserAccount");
                });

            modelBuilder.Entity("Clinic.Services.Domain.Entities.SurgerySchedule", b =>
                {
                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
